# Premarket scanner config

premarket:
  start_time: "04:00"      # ET, earliest candles to scan
  end_time: "09:50"        # ET, accounts for 15 min delay at open
  cadence_minutes: 5       # keep 5 min polling

postmarket:
  start_time: "16:00"      # ET, after regular market close
  end_time: "20:00"        # ET, last extended hours window
  cadence_minutes: 5       # same as premarket
  
scoring_weights:
  gap_percent: 0.4
  rvol: 0.3
  atr_stretch: 0.2
  catalyst: 0.1

thresholds:
  min_gap_percent: 3.0     # ignore < 3% gappers
  min_rvol: 1.5
  pump_gap_percent: 25.0   # auto-flag pump prone
  pump_rvol: 4.0
  pump_atr: 1.8

buffer:
  breakout_buffer_pct: 0.003   # 0.3% above PM high
  pullback_fib_low: 0.38
  pullback_fib_high: 0.62

risk:
  max_risk_pct: 0.5        # max NAV risk per trade
  daily_loss_cap_pct: 1.0  # stop trading for day

output:
  watchlist: "output/watchlist.csv"
  missed: "output/missed.csv"
  log: "logs/scanner.log"
  schema: "schemas/watchlist.schema.json"

pump_prone:
  earliest_entry: "09:35"
  time_stop: "11:30"

targets:
  t1: 0.10
  t2: 0.18
  stretch: 0.22

scoring_weights:
  gap_percent: 0.4
  rvol: 0.3
  atr_stretch: 0.2
  catalyst: 0.1
  atr_threshold: 2.0   # optional, default=2.0

min_liquidity: 100000  # 👈 new, safeguard for volume filters

liquidity:
  min_intraday_shares: 100000      # real-time shares traded today
  min_avg_daily_volume: 500000     # 30/60D avg, whatever your adapter returns
  min_dollar_volume: 300000        # last_price * intraday_volume
  min_price: 1.0                   # skip sub-1 tickers
  require_prices: true             # drop if last/prev_close are missing/zero
